"""add_multilingual_fields_to_project_publication_post

Revision ID: 4b08cbb499e2
Revises: ce87631b7c22
Create Date: 2026-02-18 18:26:35.797483

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b08cbb499e2"
down_revision: str | None = "ce87631b7c22"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("title_en", sa.String(length=200), nullable=True))
    op.add_column("post", sa.Column("content_en", sa.String(length=12000), nullable=True))
    op.add_column("project", sa.Column("title_en", sa.String(length=200), nullable=True))
    op.add_column("project", sa.Column("summary_en", sa.String(length=300), nullable=True))
    op.add_column("project", sa.Column("description_en", sa.String(length=8000), nullable=True))
    op.add_column("publication", sa.Column("title_en", sa.String(length=300), nullable=True))
    op.add_column("publication", sa.Column("authors_en", sa.String(length=500), nullable=True))
    op.add_column("publication", sa.Column("venue_en", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("publication", "venue_en")
    op.drop_column("publication", "authors_en")
    op.drop_column("publication", "title_en")
    op.drop_column("project", "description_en")
    op.drop_column("project", "summary_en")
    op.drop_column("project", "title_en")
    op.drop_column("post", "content_en")
    op.drop_column("post", "title_en")
    # ### end Alembic commands ###
