"""init_schema

Revision ID: 8bb452b5f586
Revises: 
Create Date: 2026-02-14 20:09:12.794439

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8bb452b5f586"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(username) >= 4', name='ck_admin_user_username_min_len'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column(
        'role',
        sa.Enum(
            'professor',
            'researcher',
            'phd',
            'master',
            'undergrad',
            name='member_role',
            native_enum=False,
        ),
        nullable=False,
    ),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('content', sa.String(length=12000), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=8000), nullable=False),
    sa.Column(
        'status',
        sa.Enum(
            'ongoing',
            'completed',
            name='project_status',
            native_enum=False,
        ),
        nullable=False,
    ),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('authors', sa.String(length=500), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('related_project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_year'), 'publication', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publication_year'), table_name='publication')
    op.drop_table('publication')
    op.drop_table('project')
    op.drop_table('post')
    op.drop_table('member')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
