"""add_member_multilingual_fields

Revision ID: ce87631b7c22
Revises: 8bb452b5f586
Create Date: 2026-02-18 18:16:32.868982

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce87631b7c22"
down_revision: str | None = "8bb452b5f586"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("member", sa.Column("name_en", sa.String(length=100), nullable=True))
    op.add_column("member", sa.Column("bio_en", sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("member", "bio_en")
    op.drop_column("member", "name_en")
    # ### end Alembic commands ###
